### ISSUE TITLE
ButtplugDeviceException: No DeviceSubtypeManagers available to scan with.

### ISSUE THREAD

**Issue by maoxs2** [buttplugio/buttplug-csharp#660]
Error while runing example Buttplug.Examples.07.FullProgram

virtual studio 2019 .netcore21+framework47
details here
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Buttplug.Examples._07.FullProgram.Program.Main() in C:\Users\C\source\repos\Boat\Boat\Program.cs:line 254

  This exception was originally thrown at this call stack:
	Buttplug.Server.DeviceManager.SendMessageAsync(Buttplug.Core.Messages.ButtplugMessage, System.Threading.CancellationToken)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
	Buttplug.Server.ButtplugServer.SendMessageAsync(Buttplug.Core.Messages.ButtplugMessage, System.Threading.CancellationToken)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	Buttplug.Client.ButtplugEmbeddedConnector.SendAsync(Buttplug.Core.Messages.ButtplugMessage, System.Threading.CancellationToken)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    ...
    [Call Stack Truncated]
Inner Exception 1:
ButtplugDeviceException: No DeviceSubtypeManagers available to scan with.
```

Device and PC bluetooth are open.

How should I deal with this?

**Comment by blackspherefollower** [comment]
The `No DeviceSubtypeManagers available to scan with.` error is raised when no device subtype managers are found.

I think they got removed at one point due to cross platform issues, but you should be able to add the references back in for your instance (either the locally or via nuget). Specifically you'll want the UWPBluetoothManager.

You may have to disable the .net core target as well (I seem to remember that being an issue since the UWPBluetoothManager only compiles for .net framework).

An alternative is just to drop the UWPBluetoothManager DLLs into the example's bin directory.

**Comment by qdot** [comment]
Add a reference to the UWPBluetoothManager project to the examples (I should probably just add those back). 

Do not drop the DLLs into the build directory, that can cause very weird issues with builds later.

**Comment by maoxs2** [comment]
Thanks, example works after adding UWPBluetoothManager by nuget.
